# Generated by Django 4.0.6 on 2022-07-05 22:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0004_alter_dependency_package'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dependency',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='for_package', to='packages.package'),
        ),
    ]
